### ISSUE TITLE
Could you please provide an example of using ABACUS?

### ISSUE THREAD

**Issue by Chentao168** [deepmodeling/DeepH-pack#1]
Can you provide a demo combining ABACUS and DeepH, including preparing the dataset, preprocessing the dataset, training the model, and inference with the model？
Thank you very much!

**Comment by mzjb** [comment]
Please find the demo in [demo_abacus.zip](https://github.com/deepmodeling/DeepH-pack/files/9526304/demo_abacus.zip).

See README.md in the zip file for more information.
