### ISSUE TITLE
Suggestion for environmental installation

### ISSUE THREAD

**Issue by TheCutestCat** [deepmodeling/DeepH-pack#2]
hi,
I would like to ask if you can make a Image of **DeepH** on the **Bohrium** which is based on the deepmodeling.
This Image can be directly based on ”**abacus-workshop**“ mirroring, that will save a lot of time to install abacus.
Then the Image can be shared on **Bohrium platform**, thus saving the users a lot of time in installation.
Thanks a lot!

link : 
(bohrium) https://bohrium.dp.tech/
(custom mirroring) https://bohrium-doc.dp.tech/docs/software/OtherSoftwares/
picture :
![图片](https://user-images.githubusercontent.com/49784245/219827919-0fe01f83-45f9-415d-a1ff-1a676b72c6a0.png)

**Comment by dingzhaohan-cn** [comment]
No problem~you will see the image before next Monday(2023-02-27)

**Comment by TheCutestCat** [comment]
Thank you very much!

**Comment by Karasawa-Shin** [comment]
> hi, I would like to ask if you can make a mirroring of **DeepH** on the **Bohrium** which is based on the deepmodeling. This mirroring can be directly based on ”**abacus-workshop**“ mirroring, that will save a lot of time to install abacus. Then the mirroring can be shared on **Bohrium platform**, thus saving the users a lot of time in installation. Thanks a lot!
> 
> link : (bohrium) https://bohrium.dp.tech/ (custom mirroring) https://bohrium-doc.dp.tech/docs/software/OtherSoftwares/ picture : ![图片](https://user-images.githubusercontent.com/49784245/219827919-0fe01f83-45f9-415d-a1ff-1a676b72c6a0.png)

Hi, Mr. Liu. I've noticed Bohrium team has just posted a mirror for DeepH: 
registry.dp.tech/dptech/abacus:3.1.4-DeepH
Hope this will help.

**Comment by TheCutestCat** [comment]
@aaaashanghai Thank you very much, this really helps me a lot!
